// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7kQLEFngqtphVMwQRWcGwxFOm5y-Vz2s',
    appId: '1:418521148309:android:2d49b3405b99451015649c',
    messagingSenderId: '418521148309',
    projectId: 'push-notification-de8ac',
    databaseURL:
        'https://push-notification-de8ac-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'push-notification-de8ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkkfHMXHCbHVA7Pnw34yIqSmzYR1aH0cc',
    appId: '1:418521148309:ios:f0833340bd4b544415649c',
    messagingSenderId: '418521148309',
    projectId: 'push-notification-de8ac',
    databaseURL:
        'https://push-notification-de8ac-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'push-notification-de8ac.firebasestorage.app',
    iosBundleId: 'com.example.jobFinder',
  );
}
