// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/job_seeker/domain/entities/cv_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6259938536795343860),
    name: 'CvEntity',
    lastPropertyId: const obx_int.IdUid(14, 4964113921733993889),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1207538836956124687),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2299839541791602808),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3698093630955224325),
        name: 'imgurl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 66880533241897104),
        name: 'fullName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7234613487388891880),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2075470539580584518),
        name: 'phone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6315398655184753703),
        name: 'address',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 431246358272069527),
        name: 'linkedinUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7344147094435549801),
        name: 'github',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4361891269131078223),
        name: 'website',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7106759127352620949),
        name: 'summary',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 646687982132890183),
        name: 'skills',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 762210432985548233),
        name: 'language',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 4964113921733993889),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 1752011921216643955),
        name: 'exp',
        targetId: const obx_int.IdUid(3, 2958712216714489942),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 3219546812901039932),
        name: 'edu',
        targetId: const obx_int.IdUid(2, 6725802805268310742),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(3, 4202022277699914132),
        name: 'project',
        targetId: const obx_int.IdUid(4, 8696494230158416435),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(4, 8632244002158821523),
        name: 'ref',
        targetId: const obx_int.IdUid(5, 6826272781873900862),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6725802805268310742),
    name: 'EduEntity',
    lastPropertyId: const obx_int.IdUid(5, 6193712538401163689),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7610203196796067102),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7673085603904195136),
        name: 'institution',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4327489590638442160),
        name: 'degree',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5726580029894799797),
        name: 'startDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6193712538401163689),
        name: 'endDate',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 2958712216714489942),
    name: 'ExpEntity',
    lastPropertyId: const obx_int.IdUid(6, 5989605703013055280),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5732695719265754262),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6496641232408011462),
        name: 'jobTitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3963647796509960709),
        name: 'companyName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8176246160748826008),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5427658708501222132),
        name: 'startDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5989605703013055280),
        name: 'endDate',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 8696494230158416435),
    name: 'Project',
    lastPropertyId: const obx_int.IdUid(7, 875565002049157813),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3509999741918515282),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5355044864817869981),
        name: 'projectName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2354140905141688890),
        name: 'projectdec',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3563334765174661690),
        name: 'projectUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6582776413910408908),
        name: 'techStack',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5597840201896334553),
        name: 'startDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 875565002049157813),
        name: 'endDate',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 6826272781873900862),
    name: 'Reference',
    lastPropertyId: const obx_int.IdUid(6, 383925896396124302),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 632721498583644986),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1450176017639566866),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1257570480234000239),
        name: 'position',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6477733939262109502),
        name: 'company',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 950646318161896680),
        name: 'phone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 383925896396124302),
        name: 'email',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 6826272781873900862),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(4, 8632244002158821523),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CvEntity: obx_int.EntityDefinition<CvEntity>(
      model: _entities[0],
      toOneRelations: (CvEntity object) => [],
      toManyRelations: (CvEntity object) => {
        obx_int.RelInfo<CvEntity>.toMany(1, object.id): object.exp,
        obx_int.RelInfo<CvEntity>.toMany(2, object.id): object.edu,
        obx_int.RelInfo<CvEntity>.toMany(3, object.id): object.project,
        obx_int.RelInfo<CvEntity>.toMany(4, object.id): object.ref,
      },
      getId: (CvEntity object) => object.id,
      setId: (CvEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CvEntity object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final imgurlOffset = fbb.writeString(object.imgurl);
        final fullNameOffset = fbb.writeString(object.fullName);
        final emailOffset = fbb.writeString(object.email);
        final phoneOffset = fbb.writeString(object.phone);
        final addressOffset = fbb.writeString(object.address);
        final linkedinUrlOffset = object.linkedinUrl == null
            ? null
            : fbb.writeString(object.linkedinUrl!);
        final githubOffset = object.github == null
            ? null
            : fbb.writeString(object.github!);
        final websiteOffset = object.website == null
            ? null
            : fbb.writeString(object.website!);
        final summaryOffset = object.summary == null
            ? null
            : fbb.writeString(object.summary!);
        final skillsOffset = fbb.writeList(
          object.skills.map(fbb.writeString).toList(growable: false),
        );
        final languageOffset = fbb.writeList(
          object.language.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, imgurlOffset);
        fbb.addOffset(3, fullNameOffset);
        fbb.addOffset(4, emailOffset);
        fbb.addOffset(5, phoneOffset);
        fbb.addOffset(6, addressOffset);
        fbb.addOffset(7, linkedinUrlOffset);
        fbb.addOffset(8, githubOffset);
        fbb.addOffset(9, websiteOffset);
        fbb.addOffset(10, summaryOffset);
        fbb.addOffset(11, skillsOffset);
        fbb.addOffset(12, languageOffset);
        fbb.addInt64(13, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final imgurlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final fullNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final phoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final linkedinUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final githubParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final websiteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final summaryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final skillsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 26, []);
        final languageParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 28, []);
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0),
        );
        final object = CvEntity(
          id: idParam,
          imgurl: imgurlParam,
          title: titleParam,
          fullName: fullNameParam,
          email: emailParam,
          phone: phoneParam,
          address: addressParam,
          linkedinUrl: linkedinUrlParam,
          github: githubParam,
          website: websiteParam,
          summary: summaryParam,
          skills: skillsParam,
          language: languageParam,
          updatedAt: updatedAtParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<CvEntity>(
          object.exp,
          store,
          obx_int.RelInfo<CvEntity>.toMany(1, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<CvEntity>(
          object.edu,
          store,
          obx_int.RelInfo<CvEntity>.toMany(2, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<CvEntity>(
          object.project,
          store,
          obx_int.RelInfo<CvEntity>.toMany(3, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<CvEntity>(
          object.ref,
          store,
          obx_int.RelInfo<CvEntity>.toMany(4, object.id),
        );
        return object;
      },
    ),
    EduEntity: obx_int.EntityDefinition<EduEntity>(
      model: _entities[1],
      toOneRelations: (EduEntity object) => [],
      toManyRelations: (EduEntity object) => {},
      getId: (EduEntity object) => object.id,
      setId: (EduEntity object, int id) {
        object.id = id;
      },
      objectToFB: (EduEntity object, fb.Builder fbb) {
        final institutionOffset = fbb.writeString(object.institution);
        final degreeOffset = fbb.writeString(object.degree);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, institutionOffset);
        fbb.addOffset(2, degreeOffset);
        fbb.addInt64(3, object.startDate.millisecondsSinceEpoch);
        fbb.addInt64(4, object.endDate.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final institutionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final degreeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final startDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final endDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final object = EduEntity(
          id: idParam,
          institution: institutionParam,
          degree: degreeParam,
          startDate: startDateParam,
          endDate: endDateParam,
        );

        return object;
      },
    ),
    ExpEntity: obx_int.EntityDefinition<ExpEntity>(
      model: _entities[2],
      toOneRelations: (ExpEntity object) => [],
      toManyRelations: (ExpEntity object) => {},
      getId: (ExpEntity object) => object.id,
      setId: (ExpEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ExpEntity object, fb.Builder fbb) {
        final jobTitleOffset = fbb.writeString(object.jobTitle);
        final companyNameOffset = fbb.writeString(object.companyName);
        final descriptionOffset = fbb.writeString(object.description);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, jobTitleOffset);
        fbb.addOffset(2, companyNameOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addInt64(4, object.startDate.millisecondsSinceEpoch);
        fbb.addInt64(5, object.endDate.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final jobTitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final companyNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final startDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final endDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final object = ExpEntity(
          id: idParam,
          jobTitle: jobTitleParam,
          companyName: companyNameParam,
          description: descriptionParam,
          startDate: startDateParam,
          endDate: endDateParam,
        );

        return object;
      },
    ),
    Project: obx_int.EntityDefinition<Project>(
      model: _entities[3],
      toOneRelations: (Project object) => [],
      toManyRelations: (Project object) => {},
      getId: (Project object) => object.id,
      setId: (Project object, int id) {
        object.id = id;
      },
      objectToFB: (Project object, fb.Builder fbb) {
        final projectNameOffset = fbb.writeString(object.projectName);
        final projectdecOffset = fbb.writeString(object.projectdec);
        final projectUrlOffset = fbb.writeString(object.projectUrl);
        final techStackOffset = fbb.writeString(object.techStack);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, projectNameOffset);
        fbb.addOffset(2, projectdecOffset);
        fbb.addOffset(3, projectUrlOffset);
        fbb.addOffset(4, techStackOffset);
        fbb.addInt64(5, object.startDate?.millisecondsSinceEpoch);
        fbb.addInt64(6, object.endDate?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final startDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final endDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final projectNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final projectdecParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final projectUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final techStackParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object =
            Project(
                id: idParam,
                projectName: projectNameParam,
                projectdec: projectdecParam,
                projectUrl: projectUrlParam,
                techStack: techStackParam,
              )
              ..startDate = startDateValue == null
                  ? null
                  : DateTime.fromMillisecondsSinceEpoch(startDateValue)
              ..endDate = endDateValue == null
                  ? null
                  : DateTime.fromMillisecondsSinceEpoch(endDateValue);

        return object;
      },
    ),
    Reference: obx_int.EntityDefinition<Reference>(
      model: _entities[4],
      toOneRelations: (Reference object) => [],
      toManyRelations: (Reference object) => {},
      getId: (Reference object) => object.id,
      setId: (Reference object, int id) {
        object.id = id;
      },
      objectToFB: (Reference object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final positionOffset = fbb.writeString(object.position);
        final companyOffset = object.company == null
            ? null
            : fbb.writeString(object.company!);
        final phoneOffset = fbb.writeString(object.phone);
        final emailOffset = fbb.writeString(object.email);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, positionOffset);
        fbb.addOffset(3, companyOffset);
        fbb.addOffset(4, phoneOffset);
        fbb.addOffset(5, emailOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final positionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final companyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final phoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final object = Reference(
          id: idParam,
          name: nameParam,
          position: positionParam,
          company: companyParam,
          phone: phoneParam,
          email: emailParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CvEntity] entity fields to define ObjectBox queries.
class CvEntity_ {
  /// See [CvEntity.id].
  static final id = obx.QueryIntegerProperty<CvEntity>(
    _entities[0].properties[0],
  );

  /// See [CvEntity.title].
  static final title = obx.QueryStringProperty<CvEntity>(
    _entities[0].properties[1],
  );

  /// See [CvEntity.imgurl].
  static final imgurl = obx.QueryStringProperty<CvEntity>(
    _entities[0].properties[2],
  );

  /// See [CvEntity.fullName].
  static final fullName = obx.QueryStringProperty<CvEntity>(
    _entities[0].properties[3],
  );

  /// See [CvEntity.email].
  static final email = obx.QueryStringProperty<CvEntity>(
    _entities[0].properties[4],
  );

  /// See [CvEntity.phone].
  static final phone = obx.QueryStringProperty<CvEntity>(
    _entities[0].properties[5],
  );

  /// See [CvEntity.address].
  static final address = obx.QueryStringProperty<CvEntity>(
    _entities[0].properties[6],
  );

  /// See [CvEntity.linkedinUrl].
  static final linkedinUrl = obx.QueryStringProperty<CvEntity>(
    _entities[0].properties[7],
  );

  /// See [CvEntity.github].
  static final github = obx.QueryStringProperty<CvEntity>(
    _entities[0].properties[8],
  );

  /// See [CvEntity.website].
  static final website = obx.QueryStringProperty<CvEntity>(
    _entities[0].properties[9],
  );

  /// See [CvEntity.summary].
  static final summary = obx.QueryStringProperty<CvEntity>(
    _entities[0].properties[10],
  );

  /// See [CvEntity.skills].
  static final skills = obx.QueryStringVectorProperty<CvEntity>(
    _entities[0].properties[11],
  );

  /// See [CvEntity.language].
  static final language = obx.QueryStringVectorProperty<CvEntity>(
    _entities[0].properties[12],
  );

  /// See [CvEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<CvEntity>(
    _entities[0].properties[13],
  );

  /// see [CvEntity.exp]
  static final exp = obx.QueryRelationToMany<CvEntity, ExpEntity>(
    _entities[0].relations[0],
  );

  /// see [CvEntity.edu]
  static final edu = obx.QueryRelationToMany<CvEntity, EduEntity>(
    _entities[0].relations[1],
  );

  /// see [CvEntity.project]
  static final project = obx.QueryRelationToMany<CvEntity, Project>(
    _entities[0].relations[2],
  );

  /// see [CvEntity.ref]
  static final ref = obx.QueryRelationToMany<CvEntity, Reference>(
    _entities[0].relations[3],
  );
}

/// [EduEntity] entity fields to define ObjectBox queries.
class EduEntity_ {
  /// See [EduEntity.id].
  static final id = obx.QueryIntegerProperty<EduEntity>(
    _entities[1].properties[0],
  );

  /// See [EduEntity.institution].
  static final institution = obx.QueryStringProperty<EduEntity>(
    _entities[1].properties[1],
  );

  /// See [EduEntity.degree].
  static final degree = obx.QueryStringProperty<EduEntity>(
    _entities[1].properties[2],
  );

  /// See [EduEntity.startDate].
  static final startDate = obx.QueryDateProperty<EduEntity>(
    _entities[1].properties[3],
  );

  /// See [EduEntity.endDate].
  static final endDate = obx.QueryDateProperty<EduEntity>(
    _entities[1].properties[4],
  );
}

/// [ExpEntity] entity fields to define ObjectBox queries.
class ExpEntity_ {
  /// See [ExpEntity.id].
  static final id = obx.QueryIntegerProperty<ExpEntity>(
    _entities[2].properties[0],
  );

  /// See [ExpEntity.jobTitle].
  static final jobTitle = obx.QueryStringProperty<ExpEntity>(
    _entities[2].properties[1],
  );

  /// See [ExpEntity.companyName].
  static final companyName = obx.QueryStringProperty<ExpEntity>(
    _entities[2].properties[2],
  );

  /// See [ExpEntity.description].
  static final description = obx.QueryStringProperty<ExpEntity>(
    _entities[2].properties[3],
  );

  /// See [ExpEntity.startDate].
  static final startDate = obx.QueryDateProperty<ExpEntity>(
    _entities[2].properties[4],
  );

  /// See [ExpEntity.endDate].
  static final endDate = obx.QueryDateProperty<ExpEntity>(
    _entities[2].properties[5],
  );
}

/// [Project] entity fields to define ObjectBox queries.
class Project_ {
  /// See [Project.id].
  static final id = obx.QueryIntegerProperty<Project>(
    _entities[3].properties[0],
  );

  /// See [Project.projectName].
  static final projectName = obx.QueryStringProperty<Project>(
    _entities[3].properties[1],
  );

  /// See [Project.projectdec].
  static final projectdec = obx.QueryStringProperty<Project>(
    _entities[3].properties[2],
  );

  /// See [Project.projectUrl].
  static final projectUrl = obx.QueryStringProperty<Project>(
    _entities[3].properties[3],
  );

  /// See [Project.techStack].
  static final techStack = obx.QueryStringProperty<Project>(
    _entities[3].properties[4],
  );

  /// See [Project.startDate].
  static final startDate = obx.QueryDateProperty<Project>(
    _entities[3].properties[5],
  );

  /// See [Project.endDate].
  static final endDate = obx.QueryDateProperty<Project>(
    _entities[3].properties[6],
  );
}

/// [Reference] entity fields to define ObjectBox queries.
class Reference_ {
  /// See [Reference.id].
  static final id = obx.QueryIntegerProperty<Reference>(
    _entities[4].properties[0],
  );

  /// See [Reference.name].
  static final name = obx.QueryStringProperty<Reference>(
    _entities[4].properties[1],
  );

  /// See [Reference.position].
  static final position = obx.QueryStringProperty<Reference>(
    _entities[4].properties[2],
  );

  /// See [Reference.company].
  static final company = obx.QueryStringProperty<Reference>(
    _entities[4].properties[3],
  );

  /// See [Reference.phone].
  static final phone = obx.QueryStringProperty<Reference>(
    _entities[4].properties[4],
  );

  /// See [Reference.email].
  static final email = obx.QueryStringProperty<Reference>(
    _entities[4].properties[5],
  );
}
